-- Oracle 테스트 데이터 생성 스크립트
-- Oracle 21c에 연결하여 실행

-- 테스트 사용자 생성 (필요시)
-- CREATE USER testuser IDENTIFIED BY testpass;
-- GRANT CONNECT, RESOURCE TO testuser;
-- GRANT CREATE SESSION TO testuser;

-- 테스트 테이블 생성
CREATE TABLE EMPLOYEES (
    EMPLOYEE_ID NUMBER(10) NOT NULL,
    FIRST_NAME VARCHAR2(50) NOT NULL,
    LAST_NAME VARCHAR2(50) NOT NULL,
    EMAIL VARCHAR2(100),
    PHONE_NUMBER VARCHAR2(20),
    HIRE_DATE DATE DEFAULT SYSDATE NOT NULL,
    SALARY NUMBER(10,2),
    DEPARTMENT_ID NUMBER(10),
    CREATED_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_EMPLOYEES PRIMARY KEY (EMPLOYEE_ID)
);

-- 테스트 데이터 삽입
INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, SALARY, DEPARTMENT_ID)
VALUES (1, 'John', 'Doe', 'john.doe@example.com', '010-1234-5678', TO_DATE('2020-01-15', 'YYYY-MM-DD'), 75000.00, 10);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, SALARY, DEPARTMENT_ID)
VALUES (2, 'Jane', 'Smith', 'jane.smith@example.com', '010-2345-6789', TO_DATE('2021-03-20', 'YYYY-MM-DD'), 82000.00, 20);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, SALARY, DEPARTMENT_ID)
VALUES (3, 'Mike', 'Johnson', 'mike.j@example.com', '010-3456-7890', TO_DATE('2019-07-10', 'YYYY-MM-DD'), 68000.00, 10);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, SALARY, DEPARTMENT_ID)
VALUES (4, 'Sarah', 'Williams', 'sarah.w@example.com', '010-4567-8901', TO_DATE('2022-02-01', 'YYYY-MM-DD'), 71000.00, 30);

INSERT INTO EMPLOYEES (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, SALARY, DEPARTMENT_ID)
VALUES (5, 'David', 'Brown', 'david.b@example.com', '010-5678-9012', TO_DATE('2020-11-05', 'YYYY-MM-DD'), 79000.00, 20);

COMMIT;

-- 인덱스 생성
CREATE INDEX IDX_EMPLOYEES_EMAIL ON EMPLOYEES(EMAIL);
CREATE INDEX IDX_EMPLOYEES_DEPT ON EMPLOYEES(DEPARTMENT_ID);

-- 코멘트 추가
COMMENT ON TABLE EMPLOYEES IS '직원 정보 테이블';
COMMENT ON COLUMN EMPLOYEES.EMPLOYEE_ID IS '직원 ID (PK)';
COMMENT ON COLUMN EMPLOYEES.FIRST_NAME IS '이름';
COMMENT ON COLUMN EMPLOYEES.LAST_NAME IS '성';

-- 확인
SELECT COUNT(*) as total_rows FROM EMPLOYEES;
SELECT * FROM EMPLOYEES ORDER BY EMPLOYEE_ID;
